sonar.projectKey=fabioformosa_n-plus-one-query-problem-detector
sonar.organization=fabioformosa
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.issue.ignore.allfile=java:S1488
